---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    # TODO: Change to ${SECRET_DOMAIN}
    external-dns.alpha.kubernetes.io/hostname: postgres.${CLUSTER_DOMAIN}
    lbipam.cilium.io/ips: "${POSTGRES_IPV4}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilies: [IPv4]
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-r
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres
#     cnpg.io/podRole: instance
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-ro
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres
#     role: replica
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-rw
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres
#     role: primary
#   sessionAffinity: None