---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./echo/ks.yaml
  - ./echo-internal/ks.yaml
  - ./echo-envoy/ks.yaml
  - ./podinfo/ks.yaml
  # - ./httpbin/ks.yaml
  # - ./httpbin2/ks.yaml
  - ./mealie/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./n8n/ks.yaml
  - ./homarr/ks.yaml
  - ./photoprism/ks.yaml
  # - ./shlink/ks.yaml
  # - ./shlink-web-client/ks.yaml
